version: '3.8'

services:
  backend:
    image: estrellaae/backend-tienda:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: estrellaae/frontend-tienda:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
