--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: registrar_venta_con_usuario(character varying, character varying, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.registrar_venta_con_usuario(p_tipo_pago character varying, p_qr_code character varying, p_id_usuario integer, OUT p_id_venta integer) RETURNS integer
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Insertar venta
    INSERT INTO public.venta (tipo_pago, qr_code)
    VALUES (p_tipo_pago, p_qr_code)
    RETURNING id_venta INTO p_id_venta;

    -- Registrar relaci¢n venta - usuario
    INSERT INTO public.venta_usuario (id_venta, id_usuario)
    VALUES (p_id_venta, p_id_usuario);

    -- Actualizar £ltimo acceso
    UPDATE public.usuarios
    SET ultimo_acceso = CURRENT_TIMESTAMP
    WHERE id = p_id_usuario;

    -- Actualizar total del turno activo
    UPDATE public.turnos_trabajo 
    SET total_ventas = total_ventas + (
        SELECT COALESCE(SUM(tp.cantidad * p.precio), 0)
        FROM public.ticket t
        JOIN public.ticket_producto tp ON t.id_ticket = tp.id_ticket
        JOIN public.producto p ON tp.id_producto = p.id_producto
        WHERE t.id_venta = p_id_venta
    )
    WHERE id_usuario = p_id_usuario AND activo = true;
END;
$$;


ALTER FUNCTION public.registrar_venta_con_usuario(p_tipo_pago character varying, p_qr_code character varying, p_id_usuario integer, OUT p_id_venta integer) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id_categoria integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    eliminado boolean DEFAULT false,
    activa boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- Name: categoria_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: codigo_barras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.codigo_barras (
    id_codigo integer NOT NULL,
    codigo character varying(255) NOT NULL,
    id_producto integer NOT NULL
);


ALTER TABLE public.codigo_barras OWNER TO postgres;

--
-- Name: codigo_barras_id_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.codigo_barras ALTER COLUMN id_codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codigo_barras_id_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: codigo_qr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.codigo_qr (
    id_qr integer NOT NULL,
    codigo_qr uuid NOT NULL,
    id_producto integer NOT NULL
);


ALTER TABLE public.codigo_qr OWNER TO postgres;

--
-- Name: codigo_qr_id_qr_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.codigo_qr ALTER COLUMN id_qr ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codigo_qr_id_qr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    mensaje text NOT NULL,
    leida boolean DEFAULT false,
    critica boolean DEFAULT false,
    fecha_creacion timestamp without time zone NOT NULL,
    fecha_expiracion timestamp without time zone NOT NULL
);


ALTER TABLE public.notificaciones OWNER TO postgres;

--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id_producto integer NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text,
    cantidad integer NOT NULL,
    precio numeric(10,2) NOT NULL,
    id_categoria integer NOT NULL,
    imagen_url text,
    CONSTRAINT producto_cantidad_check CHECK ((cantidad >= 0)),
    CONSTRAINT producto_precio_check CHECK ((precio >= (0)::numeric))
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- Name: producto_express; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto_express (
    id_express integer NOT NULL,
    id_ticket integer NOT NULL,
    codigo character varying(50) NOT NULL,
    nombre character varying(150) DEFAULT 'Venta Express'::character varying,
    cantidad integer NOT NULL,
    precio numeric(10,2) NOT NULL,
    subtotal numeric(10,2) GENERATED ALWAYS AS (((cantidad)::numeric * precio)) STORED
);


ALTER TABLE public.producto_express OWNER TO postgres;

--
-- Name: producto_express_id_express_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.producto_express_id_express_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.producto_express_id_express_seq OWNER TO postgres;

--
-- Name: producto_express_id_express_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.producto_express_id_express_seq OWNED BY public.producto_express.id_express;


--
-- Name: producto_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket (
    id_ticket integer NOT NULL,
    codigo_venta character varying(50) NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_venta integer NOT NULL
);


ALTER TABLE public.ticket OWNER TO postgres;

--
-- Name: ticket_id_ticket_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket ALTER COLUMN id_ticket ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_ticket_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_producto (
    id_ticket_producto integer NOT NULL,
    id_ticket integer NOT NULL,
    id_producto integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(12,2),
    precio_total numeric(12,2),
    nombre_personalizado text,
    CONSTRAINT ticket_producto_cantidad_check CHECK ((cantidad > 0))
);


ALTER TABLE public.ticket_producto OWNER TO postgres;

--
-- Name: ticket_producto_id_ticket_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_producto ALTER COLUMN id_ticket_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_producto_id_ticket_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: turnos_trabajo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.turnos_trabajo (
    id_turno integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha_inicio timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_fin timestamp without time zone,
    activo boolean DEFAULT true,
    total_ventas numeric(15,2) DEFAULT 0
);


ALTER TABLE public.turnos_trabajo OWNER TO postgres;

--
-- Name: turnos_trabajo_id_turno_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.turnos_trabajo ALTER COLUMN id_turno ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.turnos_trabajo_id_turno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    email character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(50) NOT NULL,
    telefono character varying(20),
    direccion text,
    reset_token text,
    reset_token_expiration timestamp without time zone,
    reset_password_token character varying(100),
    reset_password_expires timestamp without time zone,
    nombre character varying(100),
    activo boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso timestamp without time zone,
    username character varying(100)
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venta (
    id_venta integer NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    tipo_pago character varying(50) NOT NULL
);


ALTER TABLE public.venta OWNER TO postgres;

--
-- Name: venta_id_venta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venta ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venta_id_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: venta_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venta_usuario (
    id_venta_usuario integer NOT NULL,
    id_venta integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.venta_usuario OWNER TO postgres;

--
-- Name: venta_usuario_id_venta_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venta_usuario ALTER COLUMN id_venta_usuario ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.venta_usuario_id_venta_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vista_resumen_usuario_diario; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vista_resumen_usuario_diario AS
 SELECT vu.id_usuario,
    u.username,
    u.nombre AS nombre_usuario,
    date(v.fecha) AS fecha_venta,
    count(DISTINCT vu.id_venta) AS total_ventas,
    count(tp.id_ticket_producto) AS total_productos_vendidos,
    sum(((tp.cantidad)::numeric * p.precio)) AS total_importe
   FROM (((((public.venta_usuario vu
     JOIN public.usuarios u ON ((vu.id_usuario = u.id)))
     JOIN public.venta v ON ((vu.id_venta = v.id_venta)))
     LEFT JOIN public.ticket t ON ((v.id_venta = t.id_venta)))
     LEFT JOIN public.ticket_producto tp ON ((t.id_ticket = tp.id_ticket)))
     LEFT JOIN public.producto p ON ((tp.id_producto = p.id_producto)))
  GROUP BY vu.id_usuario, u.username, u.nombre, (date(v.fecha));


ALTER VIEW public.vista_resumen_usuario_diario OWNER TO postgres;

--
-- Name: vista_ventas_usuario; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vista_ventas_usuario AS
 SELECT vu.id_venta_usuario,
    vu.id_venta,
    vu.id_usuario,
    u.username,
    u.nombre AS nombre_usuario,
    u.email,
    v.fecha,
    v.tipo_pago,
    count(tp.id_ticket_producto) AS total_productos,
    sum(((tp.cantidad)::numeric * p.precio)) AS total_venta
   FROM (((((public.venta_usuario vu
     JOIN public.usuarios u ON ((vu.id_usuario = u.id)))
     JOIN public.venta v ON ((vu.id_venta = v.id_venta)))
     LEFT JOIN public.ticket t ON ((v.id_venta = t.id_venta)))
     LEFT JOIN public.ticket_producto tp ON ((t.id_ticket = tp.id_ticket)))
     LEFT JOIN public.producto p ON ((tp.id_producto = p.id_producto)))
  GROUP BY vu.id_venta_usuario, vu.id_venta, vu.id_usuario, u.username, u.nombre, u.email, v.fecha, v.tipo_pago;


ALTER VIEW public.vista_ventas_usuario OWNER TO postgres;

--
-- Name: producto_express id_express; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_express ALTER COLUMN id_express SET DEFAULT nextval('public.producto_express_id_express_seq'::regclass);


--
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria (id_categoria, nombre, descripcion, eliminado, activa, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: codigo_barras; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.codigo_barras (id_codigo, codigo, id_producto) FROM stdin;
\.


--
-- Data for Name: codigo_qr; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.codigo_qr (id_qr, codigo_qr, id_producto) FROM stdin;
\.


--
-- Data for Name: notificaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notificaciones (id, usuario_id, mensaje, leida, critica, fecha_creacion, fecha_expiracion) FROM stdin;
\.


--
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto (id_producto, nombre, descripcion, cantidad, precio, id_categoria, imagen_url) FROM stdin;
\.


--
-- Data for Name: producto_express; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto_express (id_express, id_ticket, codigo, nombre, cantidad, precio) FROM stdin;
\.


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket (id_ticket, codigo_venta, fecha, id_venta) FROM stdin;
\.


--
-- Data for Name: ticket_producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_producto (id_ticket_producto, id_ticket, id_producto, cantidad, precio_unitario, precio_total, nombre_personalizado) FROM stdin;
\.


--
-- Data for Name: turnos_trabajo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.turnos_trabajo (id_turno, id_usuario, fecha_inicio, fecha_fin, activo, total_ventas) FROM stdin;
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, email, password, rol, telefono, direccion, reset_token, reset_token_expiration, reset_password_token, reset_password_expires, nombre, activo, fecha_creacion, ultimo_acceso, username) FROM stdin;
1	nayar_garci.com@hotmail.com	$2b$12$Nz6OwBtrMfo4mvQw0wb85OesmMMgqvWfJg3mFYddJYjkGrEpI0pIa	Admin	4181240354	Universidad	\N	\N	\N	\N	Guadalupe	t	2025-12-04 21:06:27.58907	2025-12-12 13:17:17.958112	\N
\.


--
-- Data for Name: venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.venta (id_venta, fecha, tipo_pago) FROM stdin;
\.


--
-- Data for Name: venta_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.venta_usuario (id_venta_usuario, id_venta, id_usuario, fecha_registro) FROM stdin;
\.


--
-- Name: categoria_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_id_categoria_seq', 1, false);


--
-- Name: codigo_barras_id_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.codigo_barras_id_codigo_seq', 1, false);


--
-- Name: codigo_qr_id_qr_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.codigo_qr_id_qr_seq', 1, false);


--
-- Name: notificaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notificaciones_id_seq', 1, false);


--
-- Name: producto_express_id_express_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_express_id_express_seq', 1, false);


--
-- Name: producto_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_id_producto_seq', 1, false);


--
-- Name: ticket_id_ticket_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_id_ticket_seq', 1, false);


--
-- Name: ticket_producto_id_ticket_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_producto_id_ticket_producto_seq', 1, false);


--
-- Name: turnos_trabajo_id_turno_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.turnos_trabajo_id_turno_seq', 1, false);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 1, true);


--
-- Name: venta_id_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.venta_id_venta_seq', 1, false);


--
-- Name: venta_usuario_id_venta_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.venta_usuario_id_venta_usuario_seq', 1, false);


--
-- Name: categoria categoria_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_nombre_key UNIQUE (nombre);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria);


--
-- Name: codigo_barras codigo_barras_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_barras
    ADD CONSTRAINT codigo_barras_codigo_key UNIQUE (codigo);


--
-- Name: codigo_barras codigo_barras_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_barras
    ADD CONSTRAINT codigo_barras_pkey PRIMARY KEY (id_codigo);


--
-- Name: codigo_qr codigo_qr_codigo_qr_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_qr
    ADD CONSTRAINT codigo_qr_codigo_qr_key UNIQUE (codigo_qr);


--
-- Name: codigo_qr codigo_qr_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_qr
    ADD CONSTRAINT codigo_qr_pkey PRIMARY KEY (id_qr);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- Name: producto_express producto_express_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_express
    ADD CONSTRAINT producto_express_pkey PRIMARY KEY (id_express);


--
-- Name: producto producto_nombre_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_nombre_unique UNIQUE (nombre);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id_producto);


--
-- Name: ticket ticket_codigo_venta_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_codigo_venta_key UNIQUE (codigo_venta);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id_ticket);


--
-- Name: ticket_producto ticket_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_producto
    ADD CONSTRAINT ticket_producto_pkey PRIMARY KEY (id_ticket_producto);


--
-- Name: turnos_trabajo turnos_trabajo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.turnos_trabajo
    ADD CONSTRAINT turnos_trabajo_pkey PRIMARY KEY (id_turno);


--
-- Name: usuarios usuarios_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_email_key UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: venta venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT venta_pkey PRIMARY KEY (id_venta);


--
-- Name: venta_usuario venta_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_usuario
    ADD CONSTRAINT venta_usuario_pkey PRIMARY KEY (id_venta_usuario);


--
-- Name: venta_usuario venta_usuario_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_usuario
    ADD CONSTRAINT venta_usuario_unique UNIQUE (id_venta, id_usuario);


--
-- Name: idx_turnos_usuario_activo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_turnos_usuario_activo ON public.turnos_trabajo USING btree (id_usuario) WHERE (activo = true);


--
-- Name: idx_usuarios_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_usuarios_username ON public.usuarios USING btree (username) WHERE (username IS NOT NULL);


--
-- Name: idx_venta_usuario_id_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_venta_usuario_id_usuario ON public.venta_usuario USING btree (id_usuario);


--
-- Name: idx_venta_usuario_id_venta; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_venta_usuario_id_venta ON public.venta_usuario USING btree (id_venta);


--
-- Name: codigo_barras codigo_barras_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_barras
    ADD CONSTRAINT codigo_barras_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: codigo_qr codigo_qr_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.codigo_qr
    ADD CONSTRAINT codigo_qr_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto) ON DELETE CASCADE;


--
-- Name: notificaciones fk_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


--
-- Name: producto_express producto_express_id_ticket_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto_express
    ADD CONSTRAINT producto_express_id_ticket_fkey FOREIGN KEY (id_ticket) REFERENCES public.ticket(id_ticket) ON DELETE CASCADE;


--
-- Name: producto producto_id_categoria_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_id_categoria_fk FOREIGN KEY (id_categoria) REFERENCES public.categoria(id_categoria) ON UPDATE CASCADE;


--
-- Name: producto producto_id_categoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categoria(id_categoria);


--
-- Name: ticket ticket_id_venta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta);


--
-- Name: ticket_producto ticket_producto_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_producto
    ADD CONSTRAINT ticket_producto_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: ticket_producto ticket_producto_id_ticket_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_producto
    ADD CONSTRAINT ticket_producto_id_ticket_fkey FOREIGN KEY (id_ticket) REFERENCES public.ticket(id_ticket);


--
-- Name: turnos_trabajo turnos_trabajo_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.turnos_trabajo
    ADD CONSTRAINT turnos_trabajo_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: venta_usuario venta_usuario_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_usuario
    ADD CONSTRAINT venta_usuario_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: venta_usuario venta_usuario_id_venta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta_usuario
    ADD CONSTRAINT venta_usuario_id_venta_fkey FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

